interface SetupScreenProps {
    secretTokenInput: string;
    setSecretTokenInput: (val: string) => void;
    handleSetup: () => void;
}

export default function SetupScreen({ secretTokenInput, setSecretTokenInput, handleSetup }: SetupScreenProps) {
    return (
        <div className='bg-[#121212] w-[600px] h-[860px] m-0 p-0 rounded-2xl flex flex-col justify-center items-center text-white   overflow-hidden px-12'>
            <h1 className="text-3xl font-black mb-6 text-[#f3f4f6]">Machine Setup</h1>
            <p className="text-gray-400 text-center mb-8">Please enter the secret token generated by the admin to initialize this vending machine.</p>
            <input
                type="text"
                value={secretTokenInput}
                onChange={(e) => setSecretTokenInput(e.target.value)}
                placeholder="Paste Secret Token Here"
                className="w-full bg-[#1e1e1e]  rounded-xl px-4 py-4 text-white focus:outline-none focus:border-white mb-6"
            />
            <button
                onClick={handleSetup}
                className="w-full bg-white text-black font-bold py-4 rounded-xl hover:bg-gray-200 transition-colors"
            >
                Initialize Machine
            </button>
        </div>
    );
}
